# Generated by Django 3.2.7 on 2021-09-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(default='https://www.iconsdb.com/icons/preview/white/electronics-xxl.png', max_length=160),
        ),
    ]
