# Generated by Django 3.2.7 on 2021-09-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210928_1247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
